import Head from 'next/head'
import Hero from '@/components/P-home/Hero'
import { client } from 'libs/client'
import Schedule from '@/components/P-home/Schedule'
import BigNews from '@/components/P-home/BigNews'
import News from '@/components/P-home/News'
import Title from '@/components/atoms/Title'
import { useState, useEffect } from 'react'
import Question from '@/components/P-home/Question'

export default function Home({ news, hero, bigNews }) {
  const [scrolled, setScrolled] = useState(false)

  const scrollHandler = () => {
    const offset = window.scrollY
    const windowHeight = window.outerHeight

    if (offset > windowHeight / 2) {
      setScrolled(true)
    } else {
      setScrolled(false)
    }
  }

  useEffect(() => {
    window.addEventListener('scroll', scrollHandler)
    return () => {
      window.removeEventListener('scroll', scrollHandler)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Data Science League</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <header class="relative flex items-center justify-center h-screen overflow-hidden">
        <div class="text-[0.8rem] sm:text-[1.2rem] md:text-[1.6rem] lg:text-[2rem] xl:text-[2.4rem]
                  relative z-30 text-white bg-opacity-50 font-thin w-4/5 lg:w-3/5">
          Student organization specializing in data science.<br/>
          <span className="text-[1.5rem] sm:text-[2rem] md:text-[2.5rem] lg:text-[3rem] xl:text-[3.5rem] font-light">Data Science League</span><br/>
          <p className='text-[0.6rem] sm:text-[1rem] md:text-[1.3rem] lg:text-[1.7rem] xl:text-[2rem]'>
            - Connecting Possibilities to the Future with the Power of Data. -
          </p><br/>
        </div>
        <video
          autoPlay
          loop
          muted
          class="absolute z-10 w-auto min-w-full min-h-full max-w-none"
        >
          <source
            src="/sample02.mp4"
            type="video/mp4"
          />
        </video>
      </header>

      <main
        className={`
              overflow-hidden bg-cover bg-center transition-all duration-1000 bg-black`}
      >
        <div className="h-fit w-[95%] sm:w-11/12 lg:w-4/5  m-auto">
          <Title text="あいさつ"/>
          <div>
            <p className="text-white text-base w-[80%] m-auto my-4">
              私たちはデータサイエンス特化型学生団体、Data Science Leagueです。<br/>
              私たちはデータサイエンスに興味を持つ学生が集まり、<br/>
              データサイエンスに関する勉強会やハッカソンを開催しています。<br/>
              また、データサイエンスに関する情報を発信することで、<br/>
              データサイエンスに興味を持つ学生が増えることを目指しています。<br/>
              <br/>
              このサイトでは、私たちの活動やデータサイエンスに関する情報を発信していきます。<br/>
              ぜひ、私たちの活動に興味を持っていただけたら嬉しいです。<br/>
              <br/>
              また、私たちの活動に興味を持っていただけた方は、<br/>
              ぜひ、活動に参加してみてください。<br/>
              <br/>
              皆さんと一緒にデータサイエンスを学べることを楽しみにしています！<br/>
              </p>
          </div>
        </div>
        <div className="h-fit flex justify-center items-center bg-cover bg-center">
          <BigNews bigNews={bigNews} />
        </div>

        <div className="w-full h-fit mt-28">
          <div className="w-[95%] sm:w-11/12 lg:w-4/5 m-auto base-layout rounded-t-3xl space-y-2 bg-blue-950/80 text-white">
            <Title text={`最新情報 - What's New -`} />
            <News news={news} />
            <Title text={`活動 - Activities - `} />
            <Schedule />
          </div>
        </div>
        {/* <Question /> */}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: 'blogs',
    queries: {
      limit: 5, // 5件取得
    },
  })

  const hero = await client.get({
    endpoint: 'blogs',
    queries: {
      limit: 3, // 3件取得
    },
  })

  const bigNewsdata = await client.get({
    endpoint: 'blogs',
    queries: {
      limit: 3, // 3件取得
    },
  })

  return {
    props: {
      news: data.contents,
      hero: hero.contents,
      bigNews: bigNewsdata.contents,
    },
  }
}
